spring:
    h2:
        console:
            enabled: true
    datasource:
        schema: classpath:db/schema.sql
        data: classpath:db/data.sql
        sql-script-encoding: utf-8

pagehelper:
    dialect-alias: h2=com.github.pagehelper.dialect.helper.OracleDialect